##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## this si the makefile for 108trigo
##

NAME = 109tritation

all:$(NAME)

$(NAME):
	@echo '#!/usr/bin/env python3' > 109tritation
	@echo ' ' >> 109tritation
	@echo 'from main import *' >> 109tritation
	@echo ' ' >> 109tritation
	@echo 'main()' >> 109tritation
	@echo -n 'exit(0)' >> 109tritation
	@chmod 777 109tritation

clean:
	@rm -r __pycache__

fclean:
	@rm -r 109tritation

re: fclean $(NAME)