version: "3"

services:

  poll:
    build: ./poll
    restart: always
    ports:
      - "5000:80"
    networks:
      - poll-tier
  
  redis:
    image: redis
    restart: always
    ports: 
      - 6379:6379
    networks:
      - poll-tier
      - back-tier
  
  worker:
    build: ./worker
    restart: always
    networks:
      - back-tier
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  result:
    build: ./result
    restart: always
    ports:
      - 5001:80
    networks:
      - result-tier
  
networks:
  poll-tier:
  result-tier:
  back-tier:
  
volumes:
  db-data:
