##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## JFIOJFEWOI JOI JOI FEJOI EWJ OIFEJ OIFEW JOIFEW OIJFEWJ LFKE LIJFEWJ LIFEWie
##

all:
	mkdir -p ../../include
	gcc -c *.c
	ar cr libmy.a *.o
	cp libmy.a ../
	cp my.h ../../include/

clean:
	rm -f *.o
	rm -f *~
	rm -f *.a
