##
## EPITECH PROJECT, 2021
## Makefile
## File description:
## this si the makefile for 108trigo
##

NAME = 108trigo

all:$(NAME)

$(NAME):
	@echo '#!/usr/bin/env python3' > 108trigo
	@echo ' ' >> 108trigo
	@echo 'from main import *' >> 108trigo
	@echo ' ' >> 108trigo
	@echo 'main()' >> 108trigo
	@echo -n 'exit(0)' >> 108trigo
	@chmod 777 108trigo

clean:
	@rm -r __pycache__

fclean:
	@rm -r 108trigo

re: fclean $(NAME)