##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## this si the makefile for 107transfer
##

NAME = 107transfer

all:$(NAME)

$(NAME):
	@cp 107transfer.py 107transfer
	@chmod 777 107transfer

clean:
	@rm -r __pycache__

fclean:
	@rm -r 107transfer

re: fclean $(NAME)
