##
## EPITECH PROJECT, 2020
## Makefile
## File description:
## this si the makefile for 101pong
##

NAME = 106bombyx

all:$(NAME)

$(NAME):
	@cp bombyx.py 106bombyx
	@chmod 777 106bombyx

clean:
	@rm -r __pycache__

fclean:
	@rm -r 106bombyx

re: fclean $(NAME)
